# ----------------------------------------------------------------------------------------------------------------------
# Site customization
# ----------------------------------------------------------------------------------------------------------------------
# Any variable here is referenced in layouts/pages as {{site.XXX}} so something like {{site.googleId}}
# ----------------------------------------------------------------------------------------------------------------------

id: dojoconsortium
name: Dojo Consortium
domain: dojoconsortium.org
url: http://dojoconsortium.org/index.html
logo: /assets/img/logos/dojo-consortium-horiz.png
description: "Open Sourcing Enterprise Transformation."
source_url: https://github.com/devopsdojoconsortium/devopsdojoconsortium.github.io/tree/release/
license: "Licensed Creative Commons Attribution-ShareAlike 4.0 International"
license_url: https://creativecommons.org/licenses/by-sa/4.0/
crossSite: false
collapseNavDocs: true
display-search-in-header: true
custom-footer: false
contribute: true
edit-on-github: true

navigation:
  - title: OVERVIEW
    url: /overview/index.html
    context: /overview/
  - title: DOCS
    url: /docs/index.html
    context: /docs/
  - title: BLOG
    url: /blog.html
    context: /blog

projects:
 - title: About the Consortium
   url: /overview/index.html

defaults:
  -
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -
   scope:
     type: posts
   values:
     permalink: /blog/:year-:month-:day-:title.html

excerpt_separator: <!--more-->

# -------
# Jekyll
# -------
plugins:
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

exclude:
  - .*
  - pom.xml
  - "*.sh"
  - wmt-release*
  - sonar*
  - vendor
  - travis.yml
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
